
package org.motrice.signatrice.cgi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GrpServicePortType", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GrpServicePortType {


    /**
     * 
     * @param signRequest
     * @return
     *     returns org.motrice.signatrice.cgi.OrderResponseType
     * @throws GrpFault
     */
    @WebMethod(operationName = "Sign")
    @WebResult(name = "SignResponse", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "SignResponse")
    public OrderResponseType sign(
        @WebParam(name = "SignRequest", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "SignRequest")
        SignRequestType signRequest)
        throws GrpFault
    ;

    /**
     * 
     * @param collectRequest
     * @return
     *     returns org.motrice.signatrice.cgi.CollectResponseType
     * @throws GrpFault
     */
    @WebMethod(operationName = "Collect")
    @WebResult(name = "CollectResponse", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "CollectResponse")
    public CollectResponseType collect(
        @WebParam(name = "CollectRequest", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "CollectRequest")
        CollectRequestType collectRequest)
        throws GrpFault
    ;

    /**
     * 
     * @param signatureFileRequest
     * @return
     *     returns org.motrice.signatrice.cgi.OrderResponseType
     * @throws GrpFault
     */
    @WebMethod(operationName = "FileSign")
    @WebResult(name = "SignatureFileResponse", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "SignatureFileResponse")
    public OrderResponseType fileSign(
        @WebParam(name = "SignatureFileRequest", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "SignatureFileRequest")
        SignatureFileRequestType signatureFileRequest)
        throws GrpFault
    ;

    /**
     * 
     * @param authenticateRequest
     * @return
     *     returns org.motrice.signatrice.cgi.OrderResponseType
     * @throws GrpFault
     */
    @WebMethod(operationName = "Authenticate")
    @WebResult(name = "AuthenticateResponse", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "AuthenticateResponse")
    public OrderResponseType authenticate(
        @WebParam(name = "AuthenticateRequest", targetNamespace = "http://funktionstjanster.se/grp/service/v1.0.0/", partName = "AuthenticateRequest")
        AuthenticateRequestType authenticateRequest)
        throws GrpFault
    ;

}
