
package org.motrice.signatrice.cgi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GrpService", targetNamespace = "http://logic.grp.mobilityguard.com/", wsdlLocation = "http://grpt.funktionstjanster.se:18899/grp/v1?wsdl")
public class GrpService
    extends Service
{

    private final static URL GRPSERVICE_WSDL_LOCATION;
    private final static WebServiceException GRPSERVICE_EXCEPTION;
    private final static QName GRPSERVICE_QNAME = new QName("http://logic.grp.mobilityguard.com/", "GrpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://grpt.funktionstjanster.se:18899/grp/v1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GRPSERVICE_WSDL_LOCATION = url;
        GRPSERVICE_EXCEPTION = e;
    }

    public GrpService() {
        super(__getWsdlLocation(), GRPSERVICE_QNAME);
    }

    public GrpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GRPSERVICE_QNAME, features);
    }

    public GrpService(URL wsdlLocation) {
        super(wsdlLocation, GRPSERVICE_QNAME);
    }

    public GrpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GRPSERVICE_QNAME, features);
    }

    public GrpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GrpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GrpServicePortType
     */
    @WebEndpoint(name = "GrpServiceServletPort")
    public GrpServicePortType getGrpServiceServletPort() {
        return super.getPort(new QName("http://logic.grp.mobilityguard.com/", "GrpServiceServletPort"), GrpServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GrpServicePortType
     */
    @WebEndpoint(name = "GrpServiceServletPort")
    public GrpServicePortType getGrpServiceServletPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://logic.grp.mobilityguard.com/", "GrpServiceServletPort"), GrpServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GRPSERVICE_EXCEPTION!= null) {
            throw GRPSERVICE_EXCEPTION;
        }
        return GRPSERVICE_WSDL_LOCATION;
    }

}
